name-template: "Release v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
include-labels: ["major", "minor", "patch"]
categories:
  - title: "🚀 Features"
    labels: ["feature", "feat"]
  - title: "🐛 Bug Fixes"
    labels: ["fix", "bug", "bugfix"]
  - title: "🚧 Maintenance / 💡 Keep the lights on"
    label: ["chore", "deps", "dependencies", "renovate"]
  - title: "🚨 Breaking Changes"
    label: ["breaking-change"]
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels: ["major"]
  minor:
    labels: ["minor"]
  patch:
    labels: ["patch"]
  default: patch
template: |
  ## Changes

  $CHANGES
