# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
run: once

vars:
  AWS_ROOT_ACCOUNT_ID: "156589501431" # the AWS root account id

tasks:
  iam-keypair-rotate:
    desc: rotate the IAM keypair for my IAM user on the AWS root account
    cmds:
      - aws-vault rotate dnlopes

  system-cleanup:
    desc: system-wide cleanup of temporary files
    cmds:
      - task: brew-cleanup
      - task: cleanup-tmp-files
      - task: docker-cleanup

  brew-cleanup:
    internal: true
    cmd: brew cleanup

  cleanup-tmp-files:
    internal: true
    cmd: rm $HOME/.dotfiles-backups/*

  docker-cleanup:
    internal: true
    status:
      - "[[ ! -S $HOME/.rd/docker.sock ]]"
    cmd: docker system prune --volumes --force

  register-yubikey-oath:
    desc: register a new yubikey as a oath device on the AWS root account
    interactive: true
    silent: true
    requires: { AWS_ROOT_ACCOUNT_ID }
    cmd: |
      deviceName=""
      read -p "Enter device name: " deviceName
      if [ -z "$deviceName" ]; then echo "device name cannot be empty" && echo ""; exit 1; fi
      ykman oath accounts add arn:aws:iam::{{.AWS_ACCOUNT_ID}}:mfa/$deviceName
      ykman oath accounts rename arn:aws:iam::{{.AWS_ACCOUNT_ID}}:mfa/$deviceName $deviceName

  oath-code:
    desc: generates a new oath code for the specified device
    interactive: false
    silent: true
    cmd: ykman oath accounts code
