name: PR
on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, synchronize]

concurrency:
  group: pr-pre-commit-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  statuses: write
  contents: read
  checks: write
  pull-requests: read

jobs:
  pre_commmit:
    name: Pre-commit
    uses: dnlopes/Reusable.Workflows/.github/workflows/pre-commit-hooks.yaml@1c45568dc47a4ddd47de902ed36ba7cdce2a0b26 # v1
    secrets: inherit
