name: PR
on:
  pull_request:
    types: [opened, reopened, edited, labeled, unlabeled, synchronize]

concurrency:
  group: pr-pre-commit-check-${{ github.ref }}
  cancel-in-progress: true

permissions:
  statuses: write
  contents: read
  checks: write
  pull-requests: read

jobs:
  pre_commmit:
    name: Pre-commit
    uses: dnlopes/Reusable.Workflows/.github/workflows/pre-commit-hooks.yaml@c65b26e2b94c965e0aa438b96d8e328d1232cf43 # v1
    secrets: inherit
